<item>
	<Target>
		<TargetName>target</TargetName>
		<IncludePath> /project /bsp/Inc /project/Inc</IncludePath>
		<OutPutPath>obj/</OutPutPath>
		<OutPutFileName>target2</OutPutFileName>
		<DownloadFile>/dev/sda</DownloadFile>
	</Target>
	<Groups>
		<Group>
			<GroupName>manage</GroupName>
			<File>
				<FileName>list.c</FileName>
				<FilePath>list.c</FilePath>
			</File>
			<File>
				<FileName>file.c</FileName>
				<FilePath>file.c</FilePath>
			</File>
			<File>
				<FileName>main.c</FileName>
				<FilePath>main.c</FilePath>
			</File>
		</Group>
	</Groups>
</item>
